import { ModelCapability, ModelConfig } from '@/types';

export const CAPABILITY_LABELS: Record<ModelCapability, string> = {
  text: '文本生成',
  reasoning: '推理',
  vision: '视觉理解',
  image: '图片生成',
  tools: '内置工具',
};

export const BUILT_IN_TOOLS = [
  'web_search',
  'code_interpreter',
  'web_extractor',
  'image_search',
  'web_search_image',
] as const;

export const TOKEN_PLAN_MODELS: ModelConfig[] = [
  {
    id: 'qwen3.7-max',
    slug: 'qwen3.7-max',
    name: 'Qwen 3.7 Max',
    provider: '千问',
    family: 'qwen',
    color: '#86d7ea',
    description: '高质量通用推理与文本生成，支持视觉理解和内置工具。',
    bestFor: ['复杂分析', '代码辅助', '资料检索', '多模态问答'],
    capabilities: ['text', 'reasoning', 'vision', 'tools'],
    tools: [...BUILT_IN_TOOLS],
    isActive: true,
  },
  {
    id: 'qwen3.6-plus',
    slug: 'qwen3.6-plus',
    name: 'Qwen 3.6 Plus',
    provider: '千问',
    family: 'qwen',
    color: '#8fb7d6',
    description: '均衡型文本、推理与视觉理解模型，成本和能力都比较稳。',
    bestFor: ['日常问答', '长文总结', '图文理解', '工具增强'],
    capabilities: ['text', 'reasoning', 'vision', 'tools'],
    tools: [...BUILT_IN_TOOLS],
    isActive: true,
  },
  {
    id: 'qwen3.6-flash',
    slug: 'qwen3.6-flash',
    name: 'Qwen 3.6 Flash',
    provider: '千问',
    family: 'qwen',
    color: '#6fb0c4',
    description: '快速响应的轻量模型，适合并发对比和低延迟任务。',
    bestFor: ['快速草稿', '批量比较', '轻量图文问答', '工具增强'],
    capabilities: ['text', 'reasoning', 'vision', 'tools'],
    tools: [...BUILT_IN_TOOLS],
    isActive: true,
  },
  {
    id: 'qwen-image-2.0',
    slug: 'qwen-image-2.0',
    name: 'Qwen Image 2.0',
    provider: '千问',
    family: 'qwen-image',
    color: '#d07f45',
    description: '通用图片生成，适合中文海报、插画和设计草图。',
    bestFor: ['中文海报', '产品草图', '插画', '视觉灵感'],
    capabilities: ['image'],
    tools: [],
    isActive: true,
  },
  {
    id: 'qwen-image-2.0-pro',
    slug: 'qwen-image-2.0-pro',
    name: 'Qwen Image 2.0 Pro',
    provider: '千问',
    family: 'qwen-image',
    color: '#b96b3c',
    description: '更高质量的图片生成模型，适合精修级视觉输出。',
    bestFor: ['高质量海报', '精细插画', '商业视觉', '风格化图片'],
    capabilities: ['image'],
    tools: [],
    isActive: true,
  },
  {
    id: 'wan2.7-image',
    slug: 'wan2.7-image',
    name: 'Wan 2.7 Image',
    provider: '万相',
    family: 'wan',
    color: '#c87268',
    description: '万相图片生成模型，适合创意图像和设计探索。',
    bestFor: ['创意图片', '角色概念', '场景设定', '风格探索'],
    capabilities: ['image'],
    tools: [],
    isActive: true,
  },
  {
    id: 'wan2.7-image-pro',
    slug: 'wan2.7-image-pro',
    name: 'Wan 2.7 Image Pro',
    provider: '万相',
    family: 'wan',
    color: '#a95d5a',
    description: '更高质量的万相图片生成模型，适合最终图像产出。',
    bestFor: ['高质量视觉', '复杂构图', '广告概念', '摄影风格'],
    capabilities: ['image'],
    tools: [],
    isActive: true,
  },
  {
    id: 'deepseek-v4-pro',
    slug: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'DeepSeek',
    family: 'deepseek',
    color: '#aeb8c5',
    description: '强推理与文本生成，适合逻辑、代码和复杂问题拆解。',
    bestFor: ['代码审查', '数学推理', '系统设计', '复杂分析'],
    capabilities: ['text', 'reasoning'],
    tools: [],
    isActive: true,
  },
  {
    id: 'deepseek-v4-flash',
    slug: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'DeepSeek',
    family: 'deepseek',
    color: '#8d9aaa',
    description: '速度优先的 DeepSeek 模型，适合快速问答和草稿。',
    bestFor: ['快速问答', '摘要', '低延迟对比', '轻量代码'],
    capabilities: ['text', 'reasoning'],
    tools: [],
    isActive: true,
  },
  {
    id: 'deepseek-v3.2',
    slug: 'deepseek-v3.2',
    name: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    family: 'deepseek',
    color: '#98a7ba',
    description: '文本生成与推理模型，适合稳定对比基线。',
    bestFor: ['通用问答', '推理基线', '代码解释', '中文写作'],
    capabilities: ['text', 'reasoning'],
    tools: [],
    isActive: true,
  },
  {
    id: 'kimi-k2.6',
    slug: 'kimi-k2.6',
    name: 'Kimi K2.6',
    provider: '月之暗面',
    family: 'kimi',
    color: '#8fb7d6',
    description: '推理、视觉理解与文本生成，适合长上下文和图文任务。',
    bestFor: ['长文分析', '图文理解', '写作润色', '结构化总结'],
    capabilities: ['text', 'reasoning', 'vision'],
    tools: [],
    isActive: true,
  },
  {
    id: 'kimi-k2.5',
    slug: 'kimi-k2.5',
    name: 'Kimi K2.5',
    provider: '月之暗面',
    family: 'kimi',
    color: '#739fbe',
    description: '上一代 Kimi 对话模型，适合作为质量和稳定性对照。',
    bestFor: ['长文问答', '日常对话', '图文理解', '摘要'],
    capabilities: ['text', 'reasoning', 'vision'],
    tools: [],
    isActive: true,
  },
  {
    id: 'glm-5.1',
    slug: 'glm-5.1',
    name: 'GLM 5.1',
    provider: '智谱 AI',
    family: 'glm',
    color: '#9aa6b2',
    description: '智谱文本生成模型，适合中文表达和知识问答。',
    bestFor: ['中文写作', '知识问答', '摘要改写', '内容生成'],
    capabilities: ['text'],
    tools: [],
    isActive: true,
  },
  {
    id: 'glm-5',
    slug: 'glm-5',
    name: 'GLM 5',
    provider: '智谱 AI',
    family: 'glm',
    color: '#7f8a96',
    description: '稳定的 GLM 文本模型，适合对比中文输出风格。',
    bestFor: ['文案', '问答', '翻译改写', '风格对比'],
    capabilities: ['text'],
    tools: [],
    isActive: true,
  },
  {
    id: 'MiniMax-M2.5',
    slug: 'MiniMax-M2.5',
    name: 'MiniMax M2.5',
    provider: 'MiniMax',
    family: 'minimax',
    color: '#cf7e5e',
    description: '推理和文本生成模型，适合创意写作与对话比较。',
    bestFor: ['创意写作', '角色对话', '中文生成', '推理对比'],
    capabilities: ['text', 'reasoning'],
    tools: [],
    isActive: true,
  },
];

export const DEFAULT_SELECTED_MODEL_SLUGS = [
  'qwen3.7-max',
  'qwen3.6-plus',
  'deepseek-v4-pro',
];

export function findModel(slug: string) {
  return TOKEN_PLAN_MODELS.find((model) => model.slug === slug);
}

export function isImageModel(slug: string) {
  return findModel(slug)?.capabilities.includes('image') ?? false;
}
